export const FETCHING_HOTELS = 'FETCHING_HOTELS';
export const FETCHING_HOTELS_SUCCESS = 'FETCHING_HOTELS_SUCCESS';
export const FETCHING_HOTELS_ERROR = 'FETCHING_PRODUCTS_ERROR';

export const SLIDE_CAROUSEL_NEXT = 'SLIDE_CAROUSEL_NEXT';
export const SLIDE_CAROUSEL_PREV = 'SLIDE_CAROUSEL_PREV';


